// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

// Protobuf Java Version: 3.25.1
package real.grpc.tracker;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.tracker.Empty)
    com.google.protobuf.MessageOrBuilder {
}
