// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

// Protobuf Java Version: 3.25.1
package real.grpc.tracker;

public interface RobotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.tracker.Robot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 robot_id = 1;</code>
   * @return The robotId.
   */
  int getRobotId();
}
