// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

// Protobuf Java Version: 3.25.1
package real.grpc.tracker;

/**
 * Protobuf type {@code real.grpc.tracker.Robot}
 */
public final class Robot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:real.grpc.tracker.Robot)
    RobotOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Robot.newBuilder() to construct.
  private Robot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Robot() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Robot();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return real.grpc.tracker.TrackerOuterClass.internal_static_real_grpc_tracker_Robot_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return real.grpc.tracker.TrackerOuterClass.internal_static_real_grpc_tracker_Robot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            real.grpc.tracker.Robot.class, real.grpc.tracker.Robot.Builder.class);
  }

  public static final int ROBOT_ID_FIELD_NUMBER = 1;
  private int robotId_ = 0;
  /**
   * <code>int32 robot_id = 1;</code>
   * @return The robotId.
   */
  @java.lang.Override
  public int getRobotId() {
    return robotId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (robotId_ != 0) {
      output.writeInt32(1, robotId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (robotId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, robotId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof real.grpc.tracker.Robot)) {
      return super.equals(obj);
    }
    real.grpc.tracker.Robot other = (real.grpc.tracker.Robot) obj;

    if (getRobotId()
        != other.getRobotId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROBOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRobotId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static real.grpc.tracker.Robot parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static real.grpc.tracker.Robot parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static real.grpc.tracker.Robot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static real.grpc.tracker.Robot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static real.grpc.tracker.Robot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static real.grpc.tracker.Robot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static real.grpc.tracker.Robot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static real.grpc.tracker.Robot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static real.grpc.tracker.Robot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static real.grpc.tracker.Robot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static real.grpc.tracker.Robot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static real.grpc.tracker.Robot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(real.grpc.tracker.Robot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code real.grpc.tracker.Robot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:real.grpc.tracker.Robot)
      real.grpc.tracker.RobotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return real.grpc.tracker.TrackerOuterClass.internal_static_real_grpc_tracker_Robot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return real.grpc.tracker.TrackerOuterClass.internal_static_real_grpc_tracker_Robot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              real.grpc.tracker.Robot.class, real.grpc.tracker.Robot.Builder.class);
    }

    // Construct using real.grpc.tracker.Robot.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      robotId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return real.grpc.tracker.TrackerOuterClass.internal_static_real_grpc_tracker_Robot_descriptor;
    }

    @java.lang.Override
    public real.grpc.tracker.Robot getDefaultInstanceForType() {
      return real.grpc.tracker.Robot.getDefaultInstance();
    }

    @java.lang.Override
    public real.grpc.tracker.Robot build() {
      real.grpc.tracker.Robot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public real.grpc.tracker.Robot buildPartial() {
      real.grpc.tracker.Robot result = new real.grpc.tracker.Robot(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(real.grpc.tracker.Robot result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.robotId_ = robotId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof real.grpc.tracker.Robot) {
        return mergeFrom((real.grpc.tracker.Robot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(real.grpc.tracker.Robot other) {
      if (other == real.grpc.tracker.Robot.getDefaultInstance()) return this;
      if (other.getRobotId() != 0) {
        setRobotId(other.getRobotId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              robotId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int robotId_ ;
    /**
     * <code>int32 robot_id = 1;</code>
     * @return The robotId.
     */
    @java.lang.Override
    public int getRobotId() {
      return robotId_;
    }
    /**
     * <code>int32 robot_id = 1;</code>
     * @param value The robotId to set.
     * @return This builder for chaining.
     */
    public Builder setRobotId(int value) {

      robotId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 robot_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRobotId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      robotId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:real.grpc.tracker.Robot)
  }

  // @@protoc_insertion_point(class_scope:real.grpc.tracker.Robot)
  private static final real.grpc.tracker.Robot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new real.grpc.tracker.Robot();
  }

  public static real.grpc.tracker.Robot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Robot>
      PARSER = new com.google.protobuf.AbstractParser<Robot>() {
    @java.lang.Override
    public Robot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Robot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Robot> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public real.grpc.tracker.Robot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

