// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

package real.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
