// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

package real.grpc;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();

  /**
   * <code>float orientation = 3;</code>
   * @return The orientation.
   */
  float getOrientation();
}
