// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

// Protobuf Java Version: 3.25.1
package real.grpc;

public interface RobotListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.RobotList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .real.grpc.Robot robots = 1;</code>
   */
  java.util.List<real.grpc.Robot> 
      getRobotsList();
  /**
   * <code>repeated .real.grpc.Robot robots = 1;</code>
   */
  real.grpc.Robot getRobots(int index);
  /**
   * <code>repeated .real.grpc.Robot robots = 1;</code>
   */
  int getRobotsCount();
  /**
   * <code>repeated .real.grpc.Robot robots = 1;</code>
   */
  java.util.List<? extends real.grpc.RobotOrBuilder> 
      getRobotsOrBuilderList();
  /**
   * <code>repeated .real.grpc.Robot robots = 1;</code>
   */
  real.grpc.RobotOrBuilder getRobotsOrBuilder(
      int index);
}
