// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

package real.grpc;

public interface RobotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.Robot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 robot_id = 1;</code>
   * @return The robotId.
   */
  int getRobotId();
}
