// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracker.proto

package real.grpc;

public final class TrackerOuterClass {
  private TrackerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_real_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_real_grpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_real_grpc_Robot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_real_grpc_Robot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_real_grpc_RobotList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_real_grpc_RobotList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_real_grpc_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_real_grpc_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTracker.proto\022\treal.grpc\"\007\n\005Empty\"\031\n\005R" +
      "obot\022\020\n\010robot_id\030\001 \001(\005\"-\n\tRobotList\022 \n\006r" +
      "obots\030\001 \003(\0132\020.real.grpc.Robot\"5\n\010Positio" +
      "n\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\023\n\013orientation\030\003" +
      " \001(\0022{\n\007Tracker\0226\n\013GetPosition\022\020.real.gr" +
      "pc.Robot\032\023.real.grpc.Position\"\000\0228\n\014GetAl" +
      "lRobots\022\020.real.grpc.Empty\032\024.real.grpc.Ro" +
      "botList\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_real_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_real_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_real_grpc_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_real_grpc_Robot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_real_grpc_Robot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_real_grpc_Robot_descriptor,
        new java.lang.String[] { "RobotId", });
    internal_static_real_grpc_RobotList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_real_grpc_RobotList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_real_grpc_RobotList_descriptor,
        new java.lang.String[] { "Robots", });
    internal_static_real_grpc_Position_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_real_grpc_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_real_grpc_Position_descriptor,
        new java.lang.String[] { "X", "Y", "Orientation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
