# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tracker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rTracker.proto\x12\x11real.grpc.tracker\"\x07\n\x05\x45mpty\"\x19\n\x05Robot\x12\x10\n\x08robot_id\x18\x01 \x01(\x05\"5\n\tRobotList\x12(\n\x06robots\x18\x01 \x03(\x0b\x32\x18.real.grpc.tracker.Robot\"5\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x13\n\x0borientation\x18\x03 \x01(\x02\x32\x9b\x01\n\x07Tracker\x12\x46\n\x0bGetPosition\x12\x18.real.grpc.tracker.Robot\x1a\x1b.real.grpc.tracker.Position\"\x00\x12H\n\x0cGetAllRobots\x12\x18.real.grpc.tracker.Empty\x1a\x1c.real.grpc.tracker.RobotList\"\x00\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_ROBOT']._serialized_start=45
  _globals['_ROBOT']._serialized_end=70
  _globals['_ROBOTLIST']._serialized_start=72
  _globals['_ROBOTLIST']._serialized_end=125
  _globals['_POSITION']._serialized_start=127
  _globals['_POSITION']._serialized_end=180
  _globals['_TRACKER']._serialized_start=183
  _globals['_TRACKER']._serialized_end=338
# @@protoc_insertion_point(module_scope)
